/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module fsm(clk, reset, in, out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  input clk;
  input [1:0] in;
  wire [2:0] next_reg;
  output [1:0] out;
  input reset;
  wire [2:0] state_reg;
  INV_X1 _30_ (
    .A(reset),
    .ZN(_02_)
  );
  INV_X1 _31_ (
    .A(state_reg[1]),
    .ZN(_03_)
  );
  INV_X1 _32_ (
    .A(state_reg[0]),
    .ZN(_04_)
  );
  INV_X1 _33_ (
    .A(in[0]),
    .ZN(_05_)
  );
  INV_X1 _34_ (
    .A(in[1]),
    .ZN(_06_)
  );
  NOR3_X1 _35_ (
    .A1(_03_),
    .A2(state_reg[0]),
    .A3(state_reg[2]),
    .ZN(_07_)
  );
  NOR2_X1 _36_ (
    .A1(state_reg[1]),
    .A2(state_reg[0]),
    .ZN(_08_)
  );
  NOR3_X1 _37_ (
    .A1(_03_),
    .A2(_04_),
    .A3(state_reg[2]),
    .ZN(_09_)
  );
  OR3_X1 _38_ (
    .A1(_03_),
    .A2(_04_),
    .A3(state_reg[2]),
    .ZN(_10_)
  );
  XNOR2_X1 _39_ (
    .A(in[0]),
    .B(in[1]),
    .ZN(_11_)
  );
  NOR3_X1 _40_ (
    .A1(state_reg[1]),
    .A2(_04_),
    .A3(state_reg[2]),
    .ZN(_12_)
  );
  AOI22_X1 _41_ (
    .A1(state_reg[1]),
    .A2(state_reg[2]),
    .B1(_09_),
    .B2(_11_),
    .ZN(_13_)
  );
  AOI211_X1 _42_ (
    .A(state_reg[0]),
    .B(state_reg[2]),
    .C1(_05_),
    .C2(_03_),
    .ZN(_14_)
  );
  AOI22_X1 _43_ (
    .A1(in[0]),
    .A2(_12_),
    .B1(_14_),
    .B2(in[1]),
    .ZN(_15_)
  );
  NAND2_X1 _44_ (
    .A1(_13_),
    .A2(_15_),
    .ZN(next_reg[1])
  );
  NOR4_X1 _45_ (
    .A1(state_reg[1]),
    .A2(state_reg[0]),
    .A3(state_reg[2]),
    .A4(in[0]),
    .ZN(_16_)
  );
  AOI211_X1 _46_ (
    .A(state_reg[1]),
    .B(state_reg[2]),
    .C1(in[0]),
    .C2(_04_),
    .ZN(_17_)
  );
  NOR4_X1 _47_ (
    .A1(_03_),
    .A2(state_reg[2]),
    .A3(_05_),
    .A4(_06_),
    .ZN(_18_)
  );
  AOI221_X1 _48_ (
    .A(_18_),
    .B1(_17_),
    .B2(in[1]),
    .C1(state_reg[0]),
    .C2(state_reg[2]),
    .ZN(_19_)
  );
  INV_X1 _49_ (
    .A(_19_),
    .ZN(next_reg[0])
  );
  NAND3_X1 _50_ (
    .A1(in[0]),
    .A2(_06_),
    .A3(_07_),
    .ZN(_20_)
  );
  NAND2_X1 _51_ (
    .A1(state_reg[2]),
    .A2(_08_),
    .ZN(_21_)
  );
  NAND4_X1 _52_ (
    .A1(state_reg[2]),
    .A2(in[0]),
    .A3(in[1]),
    .A4(_08_),
    .ZN(_22_)
  );
  AOI21_X1 _53_ (
    .A(_16_),
    .B1(_12_),
    .B2(_06_),
    .ZN(_23_)
  );
  NAND4_X1 _54_ (
    .A1(_10_),
    .A2(_20_),
    .A3(_22_),
    .A4(_23_),
    .ZN(out[0])
  );
  MUX2_X1 _55_ (
    .A(_10_),
    .B(_21_),
    .S(_11_),
    .Z(_24_)
  );
  OAI21_X1 _56_ (
    .A(state_reg[2]),
    .B1(state_reg[0]),
    .B2(state_reg[1]),
    .ZN(_25_)
  );
  NAND3_X1 _57_ (
    .A1(_20_),
    .A2(_24_),
    .A3(_25_),
    .ZN(next_reg[2])
  );
  AOI21_X1 _58_ (
    .A(_12_),
    .B1(_11_),
    .B2(_09_),
    .ZN(_26_)
  );
  OAI21_X1 _59_ (
    .A(_26_),
    .B1(_21_),
    .B2(_06_),
    .ZN(out[1])
  );
  INV_X1 _60_ (
    .A(reset),
    .ZN(_00_)
  );
  INV_X1 _61_ (
    .A(reset),
    .ZN(_01_)
  );
  DFFR_X1 _62_ (
    .CK(clk),
    .D(next_reg[0]),
    .Q(state_reg[0]),
    .QN(_28_),
    .RN(_01_)
  );
  DFFR_X1 _63_ (
    .CK(clk),
    .D(next_reg[1]),
    .Q(state_reg[1]),
    .QN(_27_),
    .RN(_00_)
  );
  DFFR_X1 _64_ (
    .CK(clk),
    .D(next_reg[2]),
    .Q(state_reg[2]),
    .QN(_29_),
    .RN(_02_)
  );
endmodule
