/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module fsm_opt(clk, reset, in, out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  input clk;
  input [1:0] in;
  wire [4:0] next_reg;
  output [1:0] out;
  input reset;
  wire [4:0] state_reg;
  INV_X1 _45_ (
    .A(reset),
    .ZN(_04_)
  );
  INV_X1 _46_ (
    .A(state_reg[3]),
    .ZN(_05_)
  );
  INV_X1 _47_ (
    .A(state_reg[2]),
    .ZN(_06_)
  );
  INV_X1 _48_ (
    .A(state_reg[1]),
    .ZN(_07_)
  );
  INV_X1 _49_ (
    .A(state_reg[0]),
    .ZN(_08_)
  );
  INV_X1 _50_ (
    .A(state_reg[4]),
    .ZN(_09_)
  );
  INV_X1 _51_ (
    .A(in[0]),
    .ZN(_10_)
  );
  INV_X1 _52_ (
    .A(in[1]),
    .ZN(_11_)
  );
  OR2_X1 _53_ (
    .A1(state_reg[1]),
    .A2(state_reg[0]),
    .ZN(_12_)
  );
  NOR4_X1 _54_ (
    .A1(_05_),
    .A2(state_reg[2]),
    .A3(state_reg[4]),
    .A4(_12_),
    .ZN(_13_)
  );
  OR4_X1 _55_ (
    .A1(_05_),
    .A2(state_reg[2]),
    .A3(state_reg[4]),
    .A4(_12_),
    .ZN(_14_)
  );
  NOR4_X1 _56_ (
    .A1(state_reg[3]),
    .A2(_06_),
    .A3(state_reg[4]),
    .A4(_12_),
    .ZN(_15_)
  );
  OR4_X1 _57_ (
    .A1(state_reg[3]),
    .A2(_06_),
    .A3(state_reg[4]),
    .A4(_12_),
    .ZN(_16_)
  );
  OR2_X1 _58_ (
    .A1(state_reg[3]),
    .A2(state_reg[2]),
    .ZN(_17_)
  );
  OR3_X1 _59_ (
    .A1(state_reg[3]),
    .A2(state_reg[2]),
    .A3(state_reg[0]),
    .ZN(_18_)
  );
  NOR3_X1 _60_ (
    .A1(_07_),
    .A2(state_reg[4]),
    .A3(_18_),
    .ZN(_19_)
  );
  OR3_X1 _61_ (
    .A1(_07_),
    .A2(state_reg[4]),
    .A3(_18_),
    .ZN(_20_)
  );
  NAND3_X1 _62_ (
    .A1(_14_),
    .A2(_16_),
    .A3(_20_),
    .ZN(_21_)
  );
  NOR2_X1 _63_ (
    .A1(_10_),
    .A2(_11_),
    .ZN(_22_)
  );
  NOR3_X1 _64_ (
    .A1(_09_),
    .A2(_12_),
    .A3(_17_),
    .ZN(_23_)
  );
  OR3_X1 _65_ (
    .A1(_09_),
    .A2(_12_),
    .A3(_17_),
    .ZN(_24_)
  );
  NAND4_X1 _66_ (
    .A1(_14_),
    .A2(_16_),
    .A3(_20_),
    .A4(_24_),
    .ZN(_25_)
  );
  MUX2_X1 _67_ (
    .A(state_reg[3]),
    .B(_22_),
    .S(_21_),
    .Z(next_reg[3])
  );
  NOR2_X1 _68_ (
    .A1(in[0]),
    .A2(in[1]),
    .ZN(_26_)
  );
  NOR2_X1 _69_ (
    .A1(in[0]),
    .A2(_11_),
    .ZN(_27_)
  );
  AOI22_X1 _70_ (
    .A1(_13_),
    .A2(_26_),
    .B1(_27_),
    .B2(_15_),
    .ZN(_28_)
  );
  NOR4_X1 _71_ (
    .A1(state_reg[1]),
    .A2(_08_),
    .A3(state_reg[4]),
    .A4(_17_),
    .ZN(_29_)
  );
  NOR4_X1 _72_ (
    .A1(_07_),
    .A2(state_reg[4]),
    .A3(in[1]),
    .A4(_18_),
    .ZN(_30_)
  );
  AOI22_X1 _73_ (
    .A1(_22_),
    .A2(_29_),
    .B1(_30_),
    .B2(in[0]),
    .ZN(_31_)
  );
  OAI211_X1 _74_ (
    .A(_28_),
    .B(_31_),
    .C1(_06_),
    .C2(_25_),
    .ZN(next_reg[2])
  );
  OAI21_X1 _75_ (
    .A(_27_),
    .B1(_29_),
    .B2(_19_),
    .ZN(_32_)
  );
  OAI21_X1 _76_ (
    .A(_32_),
    .B1(_25_),
    .B2(_07_),
    .ZN(next_reg[1])
  );
  OAI21_X1 _77_ (
    .A(_26_),
    .B1(_19_),
    .B2(_15_),
    .ZN(_33_)
  );
  XOR2_X1 _78_ (
    .A(in[0]),
    .B(in[1]),
    .Z(_34_)
  );
  AOI22_X1 _79_ (
    .A1(_11_),
    .A2(_29_),
    .B1(_34_),
    .B2(_23_),
    .ZN(_35_)
  );
  OAI211_X1 _80_ (
    .A(_33_),
    .B(_35_),
    .C1(_08_),
    .C2(_29_),
    .ZN(next_reg[0])
  );
  NOR2_X1 _81_ (
    .A1(_13_),
    .A2(_30_),
    .ZN(_36_)
  );
  NAND3_X1 _82_ (
    .A1(in[0]),
    .A2(_11_),
    .A3(_15_),
    .ZN(_37_)
  );
  AOI22_X1 _83_ (
    .A1(_22_),
    .A2(_23_),
    .B1(_29_),
    .B2(_10_),
    .ZN(_38_)
  );
  NAND3_X1 _84_ (
    .A1(_36_),
    .A2(_37_),
    .A3(_38_),
    .ZN(out[0])
  );
  MUX2_X1 _85_ (
    .A(_24_),
    .B(_14_),
    .S(_34_),
    .Z(_39_)
  );
  OAI211_X1 _86_ (
    .A(_37_),
    .B(_39_),
    .C1(_09_),
    .C2(_25_),
    .ZN(next_reg[4])
  );
  OAI221_X1 _87_ (
    .A(_20_),
    .B1(_24_),
    .B2(_11_),
    .C1(_34_),
    .C2(_14_),
    .ZN(out[1])
  );
  INV_X1 _88_ (
    .A(reset),
    .ZN(_00_)
  );
  INV_X1 _89_ (
    .A(reset),
    .ZN(_01_)
  );
  INV_X1 _90_ (
    .A(reset),
    .ZN(_02_)
  );
  INV_X1 _91_ (
    .A(reset),
    .ZN(_03_)
  );
  DFFR_X1 _92_ (
    .CK(clk),
    .D(next_reg[3]),
    .Q(state_reg[3]),
    .QN(_40_),
    .RN(_00_)
  );
  DFFR_X1 _93_ (
    .CK(clk),
    .D(next_reg[4]),
    .Q(state_reg[4]),
    .QN(_44_),
    .RN(_04_)
  );
  DFFS_X1 _94_ (
    .CK(clk),
    .D(next_reg[0]),
    .Q(state_reg[0]),
    .QN(_43_),
    .SN(_03_)
  );
  DFFR_X1 _95_ (
    .CK(clk),
    .D(next_reg[1]),
    .Q(state_reg[1]),
    .QN(_42_),
    .RN(_02_)
  );
  DFFR_X1 _96_ (
    .CK(clk),
    .D(next_reg[2]),
    .Q(state_reg[2]),
    .QN(_41_),
    .RN(_01_)
  );
endmodule
